// scripts/test_phase0_c_p08_ssrf.cjs
// Comprehensive offline regression test suite for P0-8 SSRF defense.
// Validates safeFetch and suggest-prompts integration across 13 mandatory test cases.

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const http = require("node:http");
const https = require("node:https");
const net = require("node:net");
const zlib = require("node:zlib");
const ts = require("typescript");

const root = path.resolve(__dirname, "..");
const certDir = path.join(__dirname, "test_certs");

// 1. Compile and load production safe-fetch.ts
function loadSafeFetch() {
  const srcPath = path.join(root, "src/lib/safe-fetch.ts");
  const source = fs.readFileSync(srcPath, "utf8");
  const code = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
      esModuleInterop: true,
    },
  }).outputText;
  const mod = { exports: {} };
  const fn = new Function("require", "module", "exports", code);
  fn(require, mod, mod.exports);
  return mod.exports;
}

const {
  safeFetch,
  validateUrl,
  isPrivateOrBlockedIp,
  isPrivateOrBlockedIPv4,
  isPrivateOrBlockedIPv6,
  isObfuscatedNumericHost,
  MAX_BODY_BYTES,
  MAX_REDIRECTS,
} = loadSafeFetch();

// Read test certs generated by gen_test_certs.js
const testCa = fs.readFileSync(path.join(certDir, "test_ca.crt"));
const validCert = fs.readFileSync(path.join(certDir, "test_server_valid.crt"));
const validKey = fs.readFileSync(path.join(certDir, "test_server.key"));
const wrongCert = fs.readFileSync(path.join(certDir, "test_server_wrong.crt"));
const wrongKey = fs.readFileSync(path.join(certDir, "test_wrong.key"));

// Safe public IP mock resolver
const SAFE_PUBLIC_IP = "93.184.216.34"; // example.com public IP
const safeDnsLookup = async (_host) => [SAFE_PUBLIC_IP];

// Helper to create a custom socket connector to local port
function createLocalConnector(port, isTls = false, servername = "") {
  return (options) => {
    const sock = net.connect({ host: "127.0.0.1", port: port });
    if (!isTls) {
      return sock;
    }
    const tls = require("node:tls");
    return tls.connect({
      socket: sock,
      servername: options.servername,
      ca: options.ca,
      rejectUnauthorized: true,
    });
  };
}

async function runTests() {
  console.log("=== Phase 0-C P0-8 SSRF Defense Regression Tests Started ===");

  // Setup Local HTTP & HTTPS Test Servers
  let httpServer, httpsServerValid, httpsServerWrong;
  let httpPort, httpsPortValid, httpsPortWrong;

  // HTTP server with route dispatch
  httpServer = http.createServer((req, res) => {
    const url = new URL(req.url, "http://valid.example.com");

    if (url.pathname === "/hello") {
      res.writeHead(200, { "Content-Type": "text/html" });
      res.end("<html><body>Hello Public Web</body></html>");
    } else if (url.pathname === "/redirect-relative-1") {
      res.writeHead(302, { Location: "/redirect-relative-2" });
      res.end();
    } else if (url.pathname === "/redirect-relative-2") {
      res.writeHead(302, { Location: "/hello" });
      res.end();
    } else if (url.pathname === "/redirect-to-private") {
      res.writeHead(302, { Location: "http://127.0.0.1:80/secret" });
      res.end();
    } else if (url.pathname === "/redirect-loop-a") {
      res.writeHead(302, { Location: "/redirect-loop-b" });
      res.end();
    } else if (url.pathname === "/redirect-loop-b") {
      res.writeHead(302, { Location: "/redirect-loop-a" });
      res.end();
    } else if (url.pathname === "/redirect-excessive-1") {
      res.writeHead(302, { Location: "/redirect-excessive-2" });
      res.end();
    } else if (url.pathname === "/redirect-excessive-2") {
      res.writeHead(302, { Location: "/redirect-excessive-3" });
      res.end();
    } else if (url.pathname === "/redirect-excessive-3") {
      res.writeHead(302, { Location: "/redirect-excessive-4" });
      res.end();
    } else if (url.pathname === "/redirect-excessive-4") {
      res.writeHead(302, { Location: "/redirect-excessive-5" });
      res.end();
    } else if (url.pathname === "/redirect-excessive-5") {
      res.writeHead(200, { "Content-Type": "text/plain" });
      res.end("Too deep");
    } else if (url.pathname === "/exact-1mb") {
      const buf = Buffer.alloc(MAX_BODY_BYTES, "a");
      res.writeHead(200, { "Content-Type": "text/plain", "Content-Length": MAX_BODY_BYTES });
      res.end(buf);
    } else if (url.pathname === "/exact-1mb-plus-one") {
      const buf = Buffer.alloc(MAX_BODY_BYTES + 1, "b");
      res.writeHead(200, { "Content-Type": "text/plain" });
      res.end(buf);
    } else if (url.pathname === "/chunked-oversized") {
      res.writeHead(200, { "Content-Type": "text/plain" });
      res.end(Buffer.alloc(1200000, "c"));
    } else if (url.pathname === "/false-content-length") {
      // Lies with Content-Length: 100 but sends 1.5MB
      res.writeHead(200, { "Content-Type": "text/plain", "Content-Length": 100 });
      const big = Buffer.alloc(1500000, "d");
      res.end(big);
    } else if (url.pathname === "/gzip-normal") {
      const body = "<html><body>Compressed gzip content</body></html>";
      const gzipped = zlib.gzipSync(Buffer.from(body));
      res.writeHead(200, { "Content-Type": "text/html", "Content-Encoding": "gzip" });
      res.end(gzipped);
    } else if (url.pathname === "/zip-bomb") {
      // 2MB of zeroes compressed into a few hundred bytes
      const bigZeroes = Buffer.alloc(2 * 1024 * 1024, "0");
      const compressed = zlib.gzipSync(bigZeroes);
      res.writeHead(200, { "Content-Type": "text/html", "Content-Encoding": "gzip" });
      res.end(compressed);
    } else if (url.pathname === "/bad-encoding") {
      res.writeHead(200, { "Content-Type": "text/html", "Content-Encoding": "unsupported-compress" });
      res.end("Data");
    } else if (url.pathname === "/slow-body") {
      res.writeHead(200, { "Content-Type": "text/html" });
      setTimeout(() => {
        if (!res.writableEnded) res.end("Finally done");
      }, 300);
    } else {
      res.writeHead(404);
      res.end("Not Found");
    }
  });

  // Valid HTTPS server
  httpsServerValid = https.createServer({ cert: validCert, key: validKey }, (req, res) => {
    res.writeHead(200, { "Content-Type": "text/html" });
    res.end("<html><body>Secure HTTPS Content</body></html>");
  });

  // HTTPS server with wrong SAN (wrong.example.com)
  httpsServerWrong = https.createServer({ cert: wrongCert, key: wrongKey }, (req, res) => {
    res.writeHead(200, { "Content-Type": "text/html" });
    res.end("<html><body>Wrong Cert Content</body></html>");
  });

  await new Promise(r => httpServer.listen(0, "127.0.0.1", r));
  httpPort = httpServer.address().port;

  await new Promise(r => httpsServerValid.listen(0, "127.0.0.1", r));
  httpsPortValid = httpsServerValid.address().port;

  await new Promise(r => httpsServerWrong.listen(0, "127.0.0.1", r));
  httpsPortWrong = httpsServerWrong.address().port;

  try {
    // --- Test 1: 正常なHTTP/HTTPS取得 ---
    console.log("Test 1: 正常なHTTP/HTTPS取得");
    const httpRes = await safeFetch("http://valid.example.com/hello", {
      dnsLookup: safeDnsLookup,
      createConnection: createLocalConnector(httpPort, false),
    });
    assert.equal(httpRes.status, 200);
    assert.ok(httpRes.body.includes("Hello Public Web"));

    const httpsRes = await safeFetch("https://valid.example.com/secure", {
      dnsLookup: safeDnsLookup,
      ca: testCa,
      createConnection: createLocalConnector(httpsPortValid, true, "valid.example.com"),
    });
    assert.equal(httpsRes.status, 200);
    assert.ok(httpsRes.body.includes("Secure HTTPS Content"));
    console.log("  ✓ Test 1 Passed: 正常なHTTPおよびHTTPS取得に成功");

    // --- Test 2: private/loopback/link-local/予約IPの拒否 ---
    console.log("Test 2: private/loopback/link-local/予約IPの拒否");
    const blockedIpv4List = [
      "127.0.0.1", "127.255.255.254", "10.0.0.1", "10.254.1.2",
      "172.16.0.1", "172.31.255.254", "192.168.0.1", "192.168.254.254",
      "169.254.169.254", "169.254.1.1", "100.64.0.1", "100.127.255.254",
      "0.0.0.0", "192.0.2.1", "198.51.100.1", "203.0.113.1",
      "224.0.0.1", "240.0.0.1", "255.255.255.255"
    ];
    for (const ip of blockedIpv4List) {
      assert.equal(isPrivateOrBlockedIPv4(ip), true, `IPv4 ${ip} must be blocked`);
      assert.equal(isPrivateOrBlockedIp(ip), true, `IP ${ip} must be blocked`);
      await assert.rejects(
        async () => safeFetch(`http://${ip}/`),
        /Prohibited IP address literal|Prohibited local hostname|Unsupported protocol/
      );
    }
    // Hostname resolving to private IP
    await assert.rejects(
      async () => safeFetch("http://evil-intranet.com/", {
        dnsLookup: async () => ["10.1.2.3"]
      }),
      /Prohibited IP address \(10\.1\.2\.3\)/
    );
    console.log("  ✓ Test 2 Passed: 全てのプライベート/予約IPv4アドレスが正しく遮断された");

    // --- Test 3: IPv6・IPv4-mapped IPv6・難読化IPの拒否 ---
    console.log("Test 3: IPv6・IPv4-mapped IPv6・難読化IPの拒否");
    const blockedIpv6List = [
      "::1", "::", "fc00::1", "fd12:3456::1", "fe80::1", "ff02::1",
      "2001:db8::1", "100::1", "2002:7f00:1::",
      "::ffff:127.0.0.1", "::ffff:10.0.0.1", "::ffff:192.168.1.1"
    ];
    for (const ip of blockedIpv6List) {
      assert.equal(isPrivateOrBlockedIPv6(ip), true, `IPv6 ${ip} must be blocked`);
      assert.equal(isPrivateOrBlockedIp(ip), true, `IP ${ip} must be blocked`);
      await assert.rejects(
        async () => safeFetch(`http://[${ip}]/`),
        /Prohibited IP address/
      );
    }
    // Obfuscated hosts
    assert.equal(isObfuscatedNumericHost("2130706433"), true);
    assert.equal(isObfuscatedNumericHost("0x7f000001"), true);
    assert.equal(isObfuscatedNumericHost("0177.0.0.1"), true);
    await assert.rejects(async () => validateUrl("http://2130706433/"), /Obfuscated or raw numeric IP|Prohibited IP address literal/);
    await assert.rejects(async () => validateUrl("http://0x7f000001/"), /Obfuscated or raw numeric IP|Prohibited IP address literal/);
    await assert.rejects(async () => validateUrl("http://0177.0.0.1/"), /Obfuscated or raw numeric IP|Prohibited IP address literal/);
    console.log("  ✓ Test 3 Passed: IPv6, IPv4-mapped IPv6, および難読化IPが確実に拒否された");

    // --- Test 4: DNS検証後に応答が変わっても、未検証IPへ接続しない ---
    console.log("Test 4: DNS複数応答検証 ＆ IP Pinningの維持");
    // Dual-homed or DNS rebinding attempt: one safe public IP and one internal IP
    await assert.rejects(
      async () => safeFetch("http://mixed-dns.example.com/", {
        dnsLookup: async () => [SAFE_PUBLIC_IP, "127.0.0.1"],
      }),
      /Prohibited IP address \(127\.0\.0\.1\)/
    );
    console.log("  ✓ Test 4 Passed: 複数DNS応答内の不正IPが検知され、混在IPの拒否を確認（実lookup検証は追加テスト）");

    // --- Test 5: 正しいhostnameの証明書は成功し、hostname不一致は失敗する ---
    console.log("Test 5: TLS SNIおよび証明書ホスト名照合の検証");
    // Connection to server with mismatched SAN
    await assert.rejects(
      async () => safeFetch("https://valid.example.com/test", {
        dnsLookup: safeDnsLookup,
        ca: testCa,
        createConnection: createLocalConnector(httpsPortWrong, true, "valid.example.com"),
      }),
      /ERR_TLS_CERT_ALTNAME_INVALID|Hostname\/IP does not match/
    );
    console.log("  ✓ Test 5 Passed: 証明書のホスト名不一致が厳格に拒否された");

    // --- Test 6: 未信頼証明書は失敗する ---
    console.log("Test 6: 未信頼証明書（Untrusted CA）の拒否");
    await assert.rejects(
      async () => safeFetch("https://valid.example.com/test", {
        dnsLookup: safeDnsLookup,
        // No ca passed -> uses system root store, our test self-signed CA must fail!
        createConnection: createLocalConnector(httpsPortValid, true, "valid.example.com"),
      }),
      /DEPTH_ZERO_SELF_SIGNED_CERT|self-signed certificate|unable to verify the first certificate/
    );
    console.log("  ✓ Test 6 Passed: rejectUnauthorized が有効であり未信頼証明書が遮断された");

    // --- Test 7: 相対リダイレクト、private先への転送拒否、ループ、回数上限 ---
    console.log("Test 7: リダイレクト多層防御");
    // 7a. Relative redirect
    const redirRes = await safeFetch("http://valid.example.com/redirect-relative-1", {
      dnsLookup: safeDnsLookup,
      createConnection: createLocalConnector(httpPort, false),
    });
    assert.equal(redirRes.status, 200);
    assert.ok(redirRes.body.includes("Hello Public Web"));
    assert.equal(redirRes.finalUrl, "http://valid.example.com/hello");

    // 7b. Redirect to private IP
    await assert.rejects(
      async () => safeFetch("http://valid.example.com/redirect-to-private", {
        dnsLookup: safeDnsLookup,
        createConnection: createLocalConnector(httpPort, false),
      }),
      /Prohibited IP address literal/
    );

    // 7c. Redirect loop
    await assert.rejects(
      async () => safeFetch("http://valid.example.com/redirect-loop-a", {
        dnsLookup: safeDnsLookup,
        createConnection: createLocalConnector(httpPort, false),
      }),
      /Redirect loop detected/
    );

    // 7d. Max redirects exceeded (> 3)
    await assert.rejects(
      async () => safeFetch("http://valid.example.com/redirect-excessive-1", {
        dnsLookup: safeDnsLookup,
        createConnection: createLocalConnector(httpPort, false),
      }),
      /Maximum redirect limit of 3 exceeded/
    );
    console.log("  ✓ Test 7 Passed: 相対解決・プライベート転送拒否・ループ検知・上限3回を遵守");

    // --- Test 8: Content-Lengthなし・虚偽のContent-Lengthでも本文上限を守る ---
    console.log("Test 8: ストリーム受信中の1MB上限防御");
    // Chunked oversized
    await assert.rejects(
      async () => safeFetch("http://valid.example.com/chunked-oversized", {
        dnsLookup: safeDnsLookup,
        createConnection: createLocalConnector(httpPort, false),
      }),
      /Response body exceeded maximum allowed limit/
    );

    // False Content-Length
    await assert.rejects(
      async () => safeFetch("http://valid.example.com/false-content-length", {
        dnsLookup: safeDnsLookup,
        createConnection: createLocalConnector(httpPort, false),
      }),
      /Response body exceeded maximum allowed limit|Parse Error/
    );
    console.log("  ✓ Test 8 Passed: Content-Length偽装およびChunked転送でも1MB上限で切断");

    // --- Test 9: 上限ちょうどと上限+1 byte ---
    console.log("Test 9: 境界値（1,048,576 bytes vs 1,048,577 bytes）");
    const exactRes = await safeFetch("http://valid.example.com/exact-1mb", {
      dnsLookup: safeDnsLookup,
      createConnection: createLocalConnector(httpPort, false),
    });
    assert.equal(Buffer.byteLength(exactRes.body), MAX_BODY_BYTES);

    await assert.rejects(
      async () => safeFetch("http://valid.example.com/exact-1mb-plus-one", {
        dnsLookup: safeDnsLookup,
        createConnection: createLocalConnector(httpPort, false),
      }),
      /Response body exceeded maximum allowed limit/
    );
    console.log("  ✓ Test 9 Passed: 境界値1MBちょうどは成功、1byte超過は即時切断");

    // --- Test 10: 圧縮レスポンスの採用方針どおりの制御 ---
    console.log("Test 10: 圧縮レスポンス（gzip正常展開 ＆ zip bomb防御 ＆ 未対応拒否）");
    const gzipRes = await safeFetch("http://valid.example.com/gzip-normal", {
      dnsLookup: safeDnsLookup,
      createConnection: createLocalConnector(httpPort, false),
    });
    assert.ok(gzipRes.body.includes("Compressed gzip content"));

    // Zip bomb (2MB compressed into < 1KB)
    await assert.rejects(
      async () => safeFetch("http://valid.example.com/zip-bomb", {
        dnsLookup: safeDnsLookup,
        createConnection: createLocalConnector(httpPort, false),
      }),
      /Response body exceeded maximum allowed limit/
    );

    // Unsupported encoding
    await assert.rejects(
      async () => safeFetch("http://valid.example.com/bad-encoding", {
        dnsLookup: safeDnsLookup,
        createConnection: createLocalConnector(httpPort, false),
      }),
      /Unsupported Content-Encoding/
    );
    console.log("  ✓ Test 10 Passed: gzip正常展開・展開後1MB超過切断・未対応encoding拒否を確認");

    // --- Test 11: 遅いDNS・本文・連続リダイレクトでも全体期限を守る ---
    console.log("Test 11: 累積全体タイムアウトの遵守");
    // DNS slow
    await assert.rejects(
      async () => safeFetch("http://valid.example.com/hello", {
        timeoutMs: 150,
        dnsLookup: async () => {
          await new Promise(r => setTimeout(r, 250));
          return [SAFE_PUBLIC_IP];
        },
      }),
      /Overall request timeout/
    );

    // Slow body (body delay exceeds remaining deadline)
    await assert.rejects(
      async () => safeFetch("http://valid.example.com/slow-body", {
        timeoutMs: 150,
        dnsLookup: safeDnsLookup,
        createConnection: createLocalConnector(httpPort, false),
      }),
      /Overall request timeout/
    );
    console.log("  ✓ Test 11 Passed: DNS遅延および本文遅延が全体タイムアウトで正しく切断された");

    // --- Test 12: キャンセル後に接続・タイマーが残らない ---
    console.log("Test 12: AbortController によるキャンセルとリソース解放");
    const controller = new AbortController();
    setTimeout(() => controller.abort(), 30);
    await assert.rejects(
      async () => safeFetch("http://valid.example.com/slow-body", {
        signal: controller.signal,
        dnsLookup: safeDnsLookup,
        createConnection: createLocalConnector(httpPort, false),
      }),
      /Request aborted by caller/
    );
    console.log("  ✓ Test 12 Passed: AbortSignal によるキャンセル時の拒否を確認（解放検証は追加テスト）");

    // --- Test 13: Routeの取得失敗時に、意図しない有料API呼出しや成功応答がない ---
    console.log("Test 13: suggest-prompts Route における取得失敗時の即時遮断");
    await require("./test_phase0_c_p08_edges.cjs")();
    console.log("  ✓ Test 13 Passed: actual POST executed; rejected retrieval caused zero model calls");

    console.log("\n=======================================================");
    console.log("=== 全テスト成功 (13/13 Mandatory SSRF Tests Passed) ===");
    console.log("=======================================================\n");
  } finally {
    httpServer.close();
    httpsServerValid.close();
    httpsServerWrong.close();
  }
}

runTests().catch(err => {
  console.error("Test Suite Failed:", err);
  process.exit(1);
});
